---
- name: Create users and create files or dirs from user home dir
  hosts: all
  tasks:
   - name: Create users
     user:
      name: "{{a}}"
      password: "{{b}}"
      home: "{{c}}"
   - name: Create files/dirs in user home dir
     file:
      name: "{{d}}"
      state: "{{e}}"
...
